version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app/backend
    environment:
      - NODE_ENV=dev
    volumes:
      - ./:/home/node/app
      -  /usr/app/node_modules
    expose:
      - "8081"
    command: "npm start"